const express = require('express')
const router = express.Router()
const test = require('./test')
const user = require('./userRoutes')
const firend = require('./friendRouters')
const groups = require('./groupsRouters')
const conversation = require('./conversationRouters')
const message = require('./messageRouters')
const e2ee = require('./e2eeRouters')
const upload = require('./uploadRouters')

router.use(test)
router.use(user)
router.use(firend)
router.use(groups)
router.use(conversation)
router.use(message)
router.use(e2ee)
router.use(upload)

module.exports = router
